### ISSUE TITLE
Missing is_* functions

### ISSUE THREAD

**Issue by mooreryan** [janestreet/ppx_variants_conv#10]
The readme says that this ppx should be generating `is_*` functions, but it doesn't seem to be doing so.

E.g.,

```ocaml
module Fruit = struct
  type t = Apple | Pear [@@deriving variants]
end

let _x = Fruit.is_apple Fruit.apple
```

Gives the error

```
17 | let _x = Fruit.is_apple Fruit.apple
              ^^^^^^^^^^^^^^
Error: Unbound value Fruit.is_apple
Hint: Did you mean apple?
``` 

Is this expected behavior? (I'm using the 4.12.0 OCaml compiler and ppx_variants_conv v0.14.1.)

For reference, here's the whole generated signature:

```ocaml
sig
  type t = Apple | Pear
  val apple : t
  val pear : t
  module Variants :
    sig
      val apple : t Variant.t
      val pear : t Variant.t
      val fold :
        init:'a ->
        apple:('a -> t Variant.t -> 'b) ->
        pear:('b -> t Variant.t -> 'c) -> 'c
      val iter :
        apple:(t Variant.t -> unit) -> pear:(t Variant.t -> unit) -> unit
      val map :
        t -> apple:(t Variant.t -> 'a) -> pear:(t Variant.t -> 'a) -> 'a
      val make_matcher :
        apple:(t Variant.t -> 'a -> (unit -> 'b) * 'c) ->
        pear:(t Variant.t -> 'c -> (unit -> 'b) * 'd) -> 'a -> (t -> 'b) * 'd
      val to_rank : t -> int
      val to_name : t -> string
      val descriptions : (string * int) list
    end
end
```

**Comment by v-gb** [comment]
If you're using v.014.1, you should probably look at this README instead: https://github.com/janestreet/ppx_variants_conv/blob/v0.14.1/README.md . You'll see it doesn't have the `is_...` functions, because it's too old.

There's not a newer released version at the moment though. It's possible to use the latest version of our packages. I haven't tried this myself, but based on a quick search, maybe the command from https://github.com/janestreet/incr_map/issues/1 is the way to do it.
