### ISSUE TITLE
Warnings suddenly appearing after 0.15.0 update

### ISSUE THREAD

**Issue by chrismamo1** [janestreet/ppx_variants_conv#11]
The following code compiles fine in version 0.14.2:

```ocaml
[@@@warning "+4"]
type field =
  | A | B | C | D
  [@@deriving variants]
```

But in version 0.15.0 produces a warning:

```
File "lib/canary.ml", lines 6-8, characters 0-23:
6 | type field =
7 |   | A | B | C | D
8 |   [@@deriving variants]
Warning 4 [fragile-match]: this pattern-matching is fragile.
It will remain exhaustive when constructors are added to type field.
```

**Comment by v-gb** [comment]
I'm surprised anyone is using warning 4, because I find that warning to be so strict that it can't be used.

Obviously, we can turn off the warning in the generated code, but is this a helpful thing to do? Because the ppx generates code that goes very much against the intention of warning 4, things like `let x_val = (function X x -> Some x | _ -> None)` for `type t = X of ... | ...`.

**Comment by chrismamo1** [comment]
Warning 4 has its uses. For example, if you have a large set of possible commands/operations represented as a variant type, it can be useful to be warned if you're not exhaustively matching on all of them. E.g

```ocaml
type op =
  | Add of float * float
  | Subtract of float * float
  | Noop
  (* months later, I add *)
  | Multiply of float * float

let exec = function
  | Add a, b -> a +. b
  | Subtract a, b -> a -. b
  (* I would like the compiler to let me know about this in case I've forgotten to implement *)
  | _ -> Float.nan
```

While I do agree that this case isn't *that* common, I don't believe it's uncommon enough to disregard. While have the PPX suppress warnings is a viable solution, would it not be possible to simply have the PPX emit overly verbose code in case of functions like `x_val`? That is, with all the ignored tags generated explicitly?
